trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  targetFramework: 'netcoreapp3.1'

steps:
- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    command: 'restore'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'
- task: DotNetCoreCLI@2
  name: Build
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration) --framework $(targetFramework)'
- task: DotNetCoreCLI@2
  name: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    nobuild: true
    arguments: '--configuration $(buildConfiguration) --framework $(targetFramework)'